name: Terraform TQA Deployment

on:
  push:
    branches:
      - tqa

jobs:
  terraform:
    name: Terraform Apply TQA
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Select TQA Workspace
      run: |
        terraform workspace list
        terraform workspace select tqa || terraform workspace new tqa

    - name: Terraform Plan
      run: terraform plan -var-file="tqa.tfvars"

    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="tqa.tfvars"
